name: Waka Readme2

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: "33 23 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakatime.com/api
          SHOW_TITLE: false
          SECTION_NAME: waka2
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          CODE_LANG: txt
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true